import json

verses = [
  {"chapter": 1, "verse": 19, "text": "Such are the ways of everyone who is greedy for unjust gain; it takes away the life of its possessors.", "category": ["greed", "ill-gotten gain", "consequences"]},
  {"chapter": 3, "verse": 9, "text": "Honor the Lord with your wealth and with the firstfruits of all your produce.", "category": ["stewardship", "giving", "tithing"]},
  {"chapter": 3, "verse": 10, "text": "Then your barns will be filled with plenty, and your vats will be bursting with wine.", "category": ["abundance", "blessing", "provision"]},
  {"chapter": 3, "verse": 13, "text": "Blessed is the one who finds wisdom, and the one who gets understanding.", "category": ["wisdom", "value"]},
  {"chapter": 3, "verse": 14, "text": "For the gain from her is better than gain from silver and her profit better than gold.", "category": ["wisdom", "true value", "priorities"]},
  {"chapter": 3, "verse": 15, "text": "She is more precious than jewels, and nothing you desire can compare with her.", "category": ["wisdom", "value", "priorities"]},
  {"chapter": 3, "verse": 27, "text": "Do not withhold good from those to whom it is due, when it is in your power to do it.", "category": ["generosity", "debt payment", "fairness"]},
  {"chapter": 3, "verse": 28, "text": "Do not say to your neighbor, 'Go, and come again, tomorrow I will give it'—when you have it with you.", "category": ["debt", "integrity", "promises"]},
  {"chapter": 4, "verse": 7, "text": "The beginning of wisdom is this: Get wisdom, and whatever you get, get insight.", "category": ["wisdom", "priority", "investment"]},
  {"chapter": 5, "verse": 10, "text": "Lest strangers take their fill of your strength, and your labors go to the house of a foreigner.", "category": ["wasted resources", "consequences", "fidelity"]},
  {"chapter": 6, "verse": 1, "text": "My son, if you have put up security for your neighbor, have given your pledge for a stranger...", "category": ["debt", "co-signing", "risky relationships"]},
  {"chapter": 6, "verse": 2, "text": "If you are snared in the words of your mouth, caught in the words of your mouth.", "category": ["debt", "commitment", "trapped"]},
  {"chapter": 6, "verse": 3, "text": "Do this then, my son, and save yourself; humble yourself, and plead urgently with your neighbor.", "category": ["debt", "escape", "humility"]},
  {"chapter": 6, "verse": 5, "text": "Save yourself like a gazelle from the hand of the hunter, like a bird from the hand of the fowler.", "category": ["debt", "escape", "urgency"]},
  {"chapter": 6, "verse": 6, "text": "Go to the ant, O sluggard; consider her ways, and be wise.", "category": ["diligence", "hard work", "planning"]},
  {"chapter": 6, "verse": 7, "text": "Without having any chief, she prepares her bread in summer and gathers her food in harvest.", "category": ["diligence", "self-motivation", "planning"]},
  {"chapter": 6, "verse": 10, "text": "A little sleep, a little slumber, a little folding of the hands to rest.", "category": ["laziness", "poverty warning"]},
  {"chapter": 6, "verse": 11, "text": "And poverty will come upon you like a robber, and want like an armed man.", "category": ["poverty", "laziness consequence", "warning"]},
  {"chapter": 6, "verse": 30, "text": "People do not despise a thief if he steals to satisfy his appetite when he is hungry.", "category": ["poverty", "theft", "understanding"]},
  {"chapter": 6, "verse": 31, "text": "Yet if he is caught, he will pay sevenfold; he will give all the goods of his house.", "category": ["consequences", "restitution", "cost"]},
  {"chapter": 8, "verse": 10, "text": "Take my instruction instead of silver, and knowledge rather than choice gold.", "category": ["wisdom", "value", "priorities"]},
  {"chapter": 8, "verse": 11, "text": "For wisdom is better than jewels, and all that you may desire cannot compare with her.", "category": ["wisdom", "value"]},
  {"chapter": 8, "verse": 18, "text": "Riches and honor are with me, enduring wealth and righteousness.", "category": ["wisdom", "wealth", "honor", "righteousness"]},
  {"chapter": 8, "verse": 19, "text": "My fruit is better than gold, even fine gold, and my yield than choice silver.", "category": ["wisdom", "value", "true wealth"]},
  {"chapter": 8, "verse": 21, "text": "Granting an inheritance to those who love me, and filling their treasuries.", "category": ["inheritance", "legacy", "treasure"]},
  {"chapter": 10, "verse": 2, "text": "Treasures gained by wickedness do not profit, but righteousness delivers from death.", "category": ["unjust gain", "wealth", "righteousness"]},
  {"chapter": 10, "verse": 3, "text": "The Lord does not let the righteous go hungry, but he thwarts the craving of the wicked.", "category": ["provision", "hunger", "righteousness"]},
  {"chapter": 10, "verse": 4, "text": "A slack hand causes poverty, but the hand of the diligent makes rich.", "category": ["diligence", "laziness", "poverty", "wealth"]},
  {"chapter": 10, "verse": 5, "text": "He who gathers in summer is a prudent son, but he who sleeps in harvest is a son who brings shame.", "category": ["diligence", "planning", "opportunity"]},
  {"chapter": 10, "verse": 15, "text": "A rich man's wealth is his strong city; the poverty of the poor is their ruin.", "category": ["wealth", "poverty", "security", "ruin"]},
  {"chapter": 10, "verse": 16, "text": "The wage of the righteous leads to life, the gain of the wicked to sin.", "category": ["earnings", "righteousness", "wickedness"]},
  {"chapter": 10, "verse": 22, "text": "The blessing of the Lord makes rich, and he adds no sorrow with it.", "category": ["blessing", "wealth", "contentment"]},
  {"chapter": 10, "verse": 26, "text": "Like vinegar to the teeth and smoke to the eyes, so is the sluggard to those who send him.", "category": ["laziness", "unreliability"]},
  {"chapter": 11, "verse": 1, "text": "A false balance is an abomination to the Lord, but a just weight is his delight.", "category": ["honesty", "business", "integrity"]},
  {"chapter": 11, "verse": 4, "text": "Riches do not profit in the day of wrath, but righteousness delivers from death.", "category": ["wealth", "eternity", "righteousness"]},
  {"chapter": 11, "verse": 15, "text": "He who puts up security for a stranger will surely suffer harm, but he who hates striking hands in pledge is secure.", "category": ["debt", "co-signing", "security"]},
  {"chapter": 11, "verse": 16, "text": "A gracious woman gets honor, and violent men get riches.", "category": ["wealth", "character", "honor"]},
  {"chapter": 11, "verse": 24, "text": "One gives freely, yet grows all the richer; another withholds what he should give, and only suffers want.", "category": ["generosity", "giving", "abundance", "poverty"]},
  {"chapter": 11, "verse": 25, "text": "Whoever brings blessing will be enriched, and he who waters will himself be watered.", "category": ["generosity", "giving", "blessing", "reciprocity"]},
  {"chapter": 11, "verse": 26, "text": "The people curse him who holds back grain, but a blessing is on the head of him who sells it.", "category": ["generosity", "hoarding", "business", "blessing"]},
  {"chapter": 11, "verse": 28, "text": "Whoever trusts in his riches will fall, but the righteous will flourish like a green leaf